// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/logging (interfaces: LogStore)
//
// Generated by this command:
//
//	mockgen -typed -destination mock_logging_store.go -package mocks github.com/lusoris/lurkarr/internal/logging LogStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockLogStore is a mock of LogStore interface.
type MockLogStore struct {
	ctrl     *gomock.Controller
	recorder *MockLogStoreMockRecorder
	isgomock struct{}
}

// MockLogStoreMockRecorder is the mock recorder for MockLogStore.
type MockLogStoreMockRecorder struct {
	mock *MockLogStore
}

// NewMockLogStore creates a new mock instance.
func NewMockLogStore(ctrl *gomock.Controller) *MockLogStore {
	mock := &MockLogStore{ctrl: ctrl}
	mock.recorder = &MockLogStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStore) EXPECT() *MockLogStoreMockRecorder {
	return m.recorder
}

// InsertLogs mocks base method.
func (m *MockLogStore) InsertLogs(ctx context.Context, entries []database.LogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLogs", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLogs indicates an expected call of InsertLogs.
func (mr *MockLogStoreMockRecorder) InsertLogs(ctx, entries any) *MockLogStoreInsertLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLogs", reflect.TypeOf((*MockLogStore)(nil).InsertLogs), ctx, entries)
	return &MockLogStoreInsertLogsCall{Call: call}
}

// MockLogStoreInsertLogsCall wrap *gomock.Call
type MockLogStoreInsertLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogStoreInsertLogsCall) Return(arg0 error) *MockLogStoreInsertLogsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogStoreInsertLogsCall) Do(f func(context.Context, []database.LogEntry) error) *MockLogStoreInsertLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogStoreInsertLogsCall) DoAndReturn(f func(context.Context, []database.LogEntry) error) *MockLogStoreInsertLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
