// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/auth (interfaces: AuthStore)
//
// Generated by this command:
//
//	mockgen -typed -destination internal/mocks/mock_auth_store.go -package mocks github.com/lusoris/lurkarr/internal/auth AuthStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthStore is a mock of AuthStore interface.
type MockAuthStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuthStoreMockRecorder
	isgomock struct{}
}

// MockAuthStoreMockRecorder is the mock recorder for MockAuthStore.
type MockAuthStoreMockRecorder struct {
	mock *MockAuthStore
}

// NewMockAuthStore creates a new mock instance.
func NewMockAuthStore(ctrl *gomock.Controller) *MockAuthStore {
	mock := &MockAuthStore{ctrl: ctrl}
	mock.recorder = &MockAuthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthStore) EXPECT() *MockAuthStoreMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockAuthStore) CreateSession(ctx context.Context, userID uuid.UUID, duration time.Duration) (*database.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, userID, duration)
	ret0, _ := ret[0].(*database.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockAuthStoreMockRecorder) CreateSession(ctx, userID, duration any) *MockAuthStoreCreateSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockAuthStore)(nil).CreateSession), ctx, userID, duration)
	return &MockAuthStoreCreateSessionCall{Call: call}
}

// MockAuthStoreCreateSessionCall wrap *gomock.Call
type MockAuthStoreCreateSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthStoreCreateSessionCall) Return(arg0 *database.Session, arg1 error) *MockAuthStoreCreateSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthStoreCreateSessionCall) Do(f func(context.Context, uuid.UUID, time.Duration) (*database.Session, error)) *MockAuthStoreCreateSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthStoreCreateSessionCall) DoAndReturn(f func(context.Context, uuid.UUID, time.Duration) (*database.Session, error)) *MockAuthStoreCreateSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSession mocks base method.
func (m *MockAuthStore) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockAuthStoreMockRecorder) DeleteSession(ctx, id any) *MockAuthStoreDeleteSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockAuthStore)(nil).DeleteSession), ctx, id)
	return &MockAuthStoreDeleteSessionCall{Call: call}
}

// MockAuthStoreDeleteSessionCall wrap *gomock.Call
type MockAuthStoreDeleteSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthStoreDeleteSessionCall) Return(arg0 error) *MockAuthStoreDeleteSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthStoreDeleteSessionCall) Do(f func(context.Context, uuid.UUID) error) *MockAuthStoreDeleteSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthStoreDeleteSessionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockAuthStoreDeleteSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSession mocks base method.
func (m *MockAuthStore) GetSession(ctx context.Context, id uuid.UUID) (*database.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(*database.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockAuthStoreMockRecorder) GetSession(ctx, id any) *MockAuthStoreGetSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockAuthStore)(nil).GetSession), ctx, id)
	return &MockAuthStoreGetSessionCall{Call: call}
}

// MockAuthStoreGetSessionCall wrap *gomock.Call
type MockAuthStoreGetSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthStoreGetSessionCall) Return(arg0 *database.Session, arg1 error) *MockAuthStoreGetSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthStoreGetSessionCall) Do(f func(context.Context, uuid.UUID) (*database.Session, error)) *MockAuthStoreGetSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthStoreGetSessionCall) DoAndReturn(f func(context.Context, uuid.UUID) (*database.Session, error)) *MockAuthStoreGetSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserByID mocks base method.
func (m *MockAuthStore) GetUserByID(ctx context.Context, id uuid.UUID) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAuthStoreMockRecorder) GetUserByID(ctx, id any) *MockAuthStoreGetUserByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAuthStore)(nil).GetUserByID), ctx, id)
	return &MockAuthStoreGetUserByIDCall{Call: call}
}

// MockAuthStoreGetUserByIDCall wrap *gomock.Call
type MockAuthStoreGetUserByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthStoreGetUserByIDCall) Return(arg0 *database.User, arg1 error) *MockAuthStoreGetUserByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthStoreGetUserByIDCall) Do(f func(context.Context, uuid.UUID) (*database.User, error)) *MockAuthStoreGetUserByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthStoreGetUserByIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (*database.User, error)) *MockAuthStoreGetUserByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserByUsername mocks base method.
func (m *MockAuthStore) GetUserByUsername(ctx context.Context, username string) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockAuthStoreMockRecorder) GetUserByUsername(ctx, username any) *MockAuthStoreGetUserByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockAuthStore)(nil).GetUserByUsername), ctx, username)
	return &MockAuthStoreGetUserByUsernameCall{Call: call}
}

// MockAuthStoreGetUserByUsernameCall wrap *gomock.Call
type MockAuthStoreGetUserByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthStoreGetUserByUsernameCall) Return(arg0 *database.User, arg1 error) *MockAuthStoreGetUserByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthStoreGetUserByUsernameCall) Do(f func(context.Context, string) (*database.User, error)) *MockAuthStoreGetUserByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthStoreGetUserByUsernameCall) DoAndReturn(f func(context.Context, string) (*database.User, error)) *MockAuthStoreGetUserByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
