// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/scheduler (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -typed -destination mock_scheduler_store.go -package mocks github.com/lusoris/lurkarr/internal/scheduler Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddScheduleExecution mocks base method.
func (m *MockStore) AddScheduleExecution(ctx context.Context, scheduleID uuid.UUID, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddScheduleExecution", ctx, scheduleID, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddScheduleExecution indicates an expected call of AddScheduleExecution.
func (mr *MockStoreMockRecorder) AddScheduleExecution(ctx, scheduleID, result any) *MockStoreAddScheduleExecutionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddScheduleExecution", reflect.TypeOf((*MockStore)(nil).AddScheduleExecution), ctx, scheduleID, result)
	return &MockStoreAddScheduleExecutionCall{Call: call}
}

// MockStoreAddScheduleExecutionCall wrap *gomock.Call
type MockStoreAddScheduleExecutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreAddScheduleExecutionCall) Return(arg0 error) *MockStoreAddScheduleExecutionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreAddScheduleExecutionCall) Do(f func(context.Context, uuid.UUID, string) error) *MockStoreAddScheduleExecutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreAddScheduleExecutionCall) DoAndReturn(f func(context.Context, uuid.UUID, string) error) *MockStoreAddScheduleExecutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CleanupOldHourlyCaps mocks base method.
func (m *MockStore) CleanupOldHourlyCaps(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldHourlyCaps", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupOldHourlyCaps indicates an expected call of CleanupOldHourlyCaps.
func (mr *MockStoreMockRecorder) CleanupOldHourlyCaps(ctx any) *MockStoreCleanupOldHourlyCapsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldHourlyCaps", reflect.TypeOf((*MockStore)(nil).CleanupOldHourlyCaps), ctx)
	return &MockStoreCleanupOldHourlyCapsCall{Call: call}
}

// MockStoreCleanupOldHourlyCapsCall wrap *gomock.Call
type MockStoreCleanupOldHourlyCapsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCleanupOldHourlyCapsCall) Return(arg0 int64, arg1 error) *MockStoreCleanupOldHourlyCapsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCleanupOldHourlyCapsCall) Do(f func(context.Context) (int64, error)) *MockStoreCleanupOldHourlyCapsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCleanupOldHourlyCapsCall) DoAndReturn(f func(context.Context) (int64, error)) *MockStoreCleanupOldHourlyCapsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAppSettings mocks base method.
func (m *MockStore) GetAppSettings(ctx context.Context, appType database.AppType) (*database.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSettings", ctx, appType)
	ret0, _ := ret[0].(*database.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSettings indicates an expected call of GetAppSettings.
func (mr *MockStoreMockRecorder) GetAppSettings(ctx, appType any) *MockStoreGetAppSettingsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSettings", reflect.TypeOf((*MockStore)(nil).GetAppSettings), ctx, appType)
	return &MockStoreGetAppSettingsCall{Call: call}
}

// MockStoreGetAppSettingsCall wrap *gomock.Call
type MockStoreGetAppSettingsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetAppSettingsCall) Return(arg0 *database.AppSettings, arg1 error) *MockStoreGetAppSettingsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetAppSettingsCall) Do(f func(context.Context, database.AppType) (*database.AppSettings, error)) *MockStoreGetAppSettingsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetAppSettingsCall) DoAndReturn(f func(context.Context, database.AppType) (*database.AppSettings, error)) *MockStoreGetAppSettingsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListInstances mocks base method.
func (m *MockStore) ListInstances(ctx context.Context, appType database.AppType) ([]database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, appType)
	ret0, _ := ret[0].([]database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockStoreMockRecorder) ListInstances(ctx, appType any) *MockStoreListInstancesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockStore)(nil).ListInstances), ctx, appType)
	return &MockStoreListInstancesCall{Call: call}
}

// MockStoreListInstancesCall wrap *gomock.Call
type MockStoreListInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreListInstancesCall) Return(arg0 []database.AppInstance, arg1 error) *MockStoreListInstancesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreListInstancesCall) Do(f func(context.Context, database.AppType) ([]database.AppInstance, error)) *MockStoreListInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreListInstancesCall) DoAndReturn(f func(context.Context, database.AppType) ([]database.AppInstance, error)) *MockStoreListInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSchedules mocks base method.
func (m *MockStore) ListSchedules(ctx context.Context) ([]database.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx)
	ret0, _ := ret[0].([]database.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockStoreMockRecorder) ListSchedules(ctx any) *MockStoreListSchedulesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockStore)(nil).ListSchedules), ctx)
	return &MockStoreListSchedulesCall{Call: call}
}

// MockStoreListSchedulesCall wrap *gomock.Call
type MockStoreListSchedulesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreListSchedulesCall) Return(arg0 []database.Schedule, arg1 error) *MockStoreListSchedulesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreListSchedulesCall) Do(f func(context.Context) ([]database.Schedule, error)) *MockStoreListSchedulesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreListSchedulesCall) DoAndReturn(f func(context.Context) ([]database.Schedule, error)) *MockStoreListSchedulesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateAppSettings mocks base method.
func (m *MockStore) UpdateAppSettings(ctx context.Context, s *database.AppSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppSettings indicates an expected call of UpdateAppSettings.
func (mr *MockStoreMockRecorder) UpdateAppSettings(ctx, s any) *MockStoreUpdateAppSettingsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppSettings", reflect.TypeOf((*MockStore)(nil).UpdateAppSettings), ctx, s)
	return &MockStoreUpdateAppSettingsCall{Call: call}
}

// MockStoreUpdateAppSettingsCall wrap *gomock.Call
type MockStoreUpdateAppSettingsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreUpdateAppSettingsCall) Return(arg0 error) *MockStoreUpdateAppSettingsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreUpdateAppSettingsCall) Do(f func(context.Context, *database.AppSettings) error) *MockStoreUpdateAppSettingsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreUpdateAppSettingsCall) DoAndReturn(f func(context.Context, *database.AppSettings) error) *MockStoreUpdateAppSettingsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateInstance mocks base method.
func (m *MockStore) UpdateInstance(ctx context.Context, id uuid.UUID, name, apiURL, apiKey string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", ctx, id, name, apiURL, apiKey, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockStoreMockRecorder) UpdateInstance(ctx, id, name, apiURL, apiKey, enabled any) *MockStoreUpdateInstanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockStore)(nil).UpdateInstance), ctx, id, name, apiURL, apiKey, enabled)
	return &MockStoreUpdateInstanceCall{Call: call}
}

// MockStoreUpdateInstanceCall wrap *gomock.Call
type MockStoreUpdateInstanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreUpdateInstanceCall) Return(arg0 error) *MockStoreUpdateInstanceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreUpdateInstanceCall) Do(f func(context.Context, uuid.UUID, string, string, string, bool) error) *MockStoreUpdateInstanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreUpdateInstanceCall) DoAndReturn(f func(context.Context, uuid.UUID, string, string, string, bool) error) *MockStoreUpdateInstanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
