// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/autoimport (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=autoimport github.com/lusoris/lurkarr/internal/autoimport Store
//

// Package autoimport is a generated GoMock package.
package autoimport

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetGeneralSettings mocks base method.
func (m *MockStore) GetGeneralSettings(ctx context.Context) (*database.GeneralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx)
	ret0, _ := ret[0].(*database.GeneralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockStoreMockRecorder) GetGeneralSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockStore)(nil).GetGeneralSettings), ctx)
}

// ListEnabledInstances mocks base method.
func (m *MockStore) ListEnabledInstances(ctx context.Context, appType database.AppType) ([]database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledInstances", ctx, appType)
	ret0, _ := ret[0].([]database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledInstances indicates an expected call of ListEnabledInstances.
func (mr *MockStoreMockRecorder) ListEnabledInstances(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledInstances", reflect.TypeOf((*MockStore)(nil).ListEnabledInstances), ctx, appType)
}

// LogAutoImport mocks base method.
func (m *MockStore) LogAutoImport(ctx context.Context, appType database.AppType, instanceID uuid.UUID, mediaID int, mediaTitle string, queueItemID int, action, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAutoImport", ctx, appType, instanceID, mediaID, mediaTitle, queueItemID, action, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAutoImport indicates an expected call of LogAutoImport.
func (mr *MockStoreMockRecorder) LogAutoImport(ctx, appType, instanceID, mediaID, mediaTitle, queueItemID, action, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAutoImport", reflect.TypeOf((*MockStore)(nil).LogAutoImport), ctx, appType, instanceID, mediaID, mediaTitle, queueItemID, action, reason)
}
