// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/api (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=api github.com/lusoris/lurkarr/internal/api Store
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CountBlocklistRulesBySource mocks base method.
func (m *MockStore) CountBlocklistRulesBySource(ctx context.Context, sourceID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBlocklistRulesBySource", ctx, sourceID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBlocklistRulesBySource indicates an expected call of CountBlocklistRulesBySource.
func (mr *MockStoreMockRecorder) CountBlocklistRulesBySource(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBlocklistRulesBySource", reflect.TypeOf((*MockStore)(nil).CountBlocklistRulesBySource), ctx, sourceID)
}

// CreateBlocklistRule mocks base method.
func (m *MockStore) CreateBlocklistRule(ctx context.Context, r *database.BlocklistRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlocklistRule", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlocklistRule indicates an expected call of CreateBlocklistRule.
func (mr *MockStoreMockRecorder) CreateBlocklistRule(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlocklistRule", reflect.TypeOf((*MockStore)(nil).CreateBlocklistRule), ctx, r)
}

// CreateBlocklistSource mocks base method.
func (m *MockStore) CreateBlocklistSource(ctx context.Context, s *database.BlocklistSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlocklistSource", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlocklistSource indicates an expected call of CreateBlocklistSource.
func (mr *MockStoreMockRecorder) CreateBlocklistSource(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlocklistSource", reflect.TypeOf((*MockStore)(nil).CreateBlocklistSource), ctx, s)
}

// CreateInstance mocks base method.
func (m *MockStore) CreateInstance(ctx context.Context, appType database.AppType, name, apiURL, apiKey string) (*database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, appType, name, apiURL, apiKey)
	ret0, _ := ret[0].(*database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockStoreMockRecorder) CreateInstance(ctx, appType, name, apiURL, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockStore)(nil).CreateInstance), ctx, appType, name, apiURL, apiKey)
}

// CreateNotificationProvider mocks base method.
func (m *MockStore) CreateNotificationProvider(ctx context.Context, p *database.NotificationProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationProvider", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotificationProvider indicates an expected call of CreateNotificationProvider.
func (mr *MockStoreMockRecorder) CreateNotificationProvider(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationProvider", reflect.TypeOf((*MockStore)(nil).CreateNotificationProvider), ctx, p)
}

// CreateSchedule mocks base method.
func (m *MockStore) CreateSchedule(ctx context.Context, s *database.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockStoreMockRecorder) CreateSchedule(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockStore)(nil).CreateSchedule), ctx, s)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, username, passwordHash string) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, passwordHash)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, username, passwordHash)
}

// DeleteBlocklistRule mocks base method.
func (m *MockStore) DeleteBlocklistRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlocklistRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlocklistRule indicates an expected call of DeleteBlocklistRule.
func (mr *MockStoreMockRecorder) DeleteBlocklistRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlocklistRule", reflect.TypeOf((*MockStore)(nil).DeleteBlocklistRule), ctx, id)
}

// DeleteBlocklistRulesBySource mocks base method.
func (m *MockStore) DeleteBlocklistRulesBySource(ctx context.Context, sourceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlocklistRulesBySource", ctx, sourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlocklistRulesBySource indicates an expected call of DeleteBlocklistRulesBySource.
func (mr *MockStoreMockRecorder) DeleteBlocklistRulesBySource(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlocklistRulesBySource", reflect.TypeOf((*MockStore)(nil).DeleteBlocklistRulesBySource), ctx, sourceID)
}

// DeleteBlocklistSource mocks base method.
func (m *MockStore) DeleteBlocklistSource(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlocklistSource", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlocklistSource indicates an expected call of DeleteBlocklistSource.
func (mr *MockStoreMockRecorder) DeleteBlocklistSource(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlocklistSource", reflect.TypeOf((*MockStore)(nil).DeleteBlocklistSource), ctx, id)
}

// DeleteHistory mocks base method.
func (m *MockStore) DeleteHistory(ctx context.Context, appType database.AppType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHistory", ctx, appType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHistory indicates an expected call of DeleteHistory.
func (mr *MockStoreMockRecorder) DeleteHistory(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHistory", reflect.TypeOf((*MockStore)(nil).DeleteHistory), ctx, appType)
}

// DeleteInstance mocks base method.
func (m *MockStore) DeleteInstance(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockStoreMockRecorder) DeleteInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockStore)(nil).DeleteInstance), ctx, id)
}

// DeleteNotificationProvider mocks base method.
func (m *MockStore) DeleteNotificationProvider(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotificationProvider", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotificationProvider indicates an expected call of DeleteNotificationProvider.
func (mr *MockStoreMockRecorder) DeleteNotificationProvider(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotificationProvider", reflect.TypeOf((*MockStore)(nil).DeleteNotificationProvider), ctx, id)
}

// DeleteSchedule mocks base method.
func (m *MockStore) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockStoreMockRecorder) DeleteSchedule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockStore)(nil).DeleteSchedule), ctx, id)
}

// DeleteSession mocks base method.
func (m *MockStore) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStoreMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStore)(nil).DeleteSession), ctx, id)
}

// GetAllHourlyCaps mocks base method.
func (m *MockStore) GetAllHourlyCaps(ctx context.Context) ([]database.HourlyCap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHourlyCaps", ctx)
	ret0, _ := ret[0].([]database.HourlyCap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHourlyCaps indicates an expected call of GetAllHourlyCaps.
func (mr *MockStoreMockRecorder) GetAllHourlyCaps(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHourlyCaps", reflect.TypeOf((*MockStore)(nil).GetAllHourlyCaps), ctx)
}

// GetAllStats mocks base method.
func (m *MockStore) GetAllStats(ctx context.Context) ([]database.LurkStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStats", ctx)
	ret0, _ := ret[0].([]database.LurkStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStats indicates an expected call of GetAllStats.
func (mr *MockStoreMockRecorder) GetAllStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStats", reflect.TypeOf((*MockStore)(nil).GetAllStats), ctx)
}

// GetAppSettings mocks base method.
func (m *MockStore) GetAppSettings(ctx context.Context, appType database.AppType) (*database.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSettings", ctx, appType)
	ret0, _ := ret[0].(*database.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSettings indicates an expected call of GetAppSettings.
func (mr *MockStoreMockRecorder) GetAppSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSettings", reflect.TypeOf((*MockStore)(nil).GetAppSettings), ctx, appType)
}

// GetAutoImportLog mocks base method.
func (m *MockStore) GetAutoImportLog(ctx context.Context, appType database.AppType, limit int) ([]database.AutoImportLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoImportLog", ctx, appType, limit)
	ret0, _ := ret[0].([]database.AutoImportLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoImportLog indicates an expected call of GetAutoImportLog.
func (mr *MockStoreMockRecorder) GetAutoImportLog(ctx, appType, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoImportLog", reflect.TypeOf((*MockStore)(nil).GetAutoImportLog), ctx, appType, limit)
}

// GetBlocklistLog mocks base method.
func (m *MockStore) GetBlocklistLog(ctx context.Context, appType database.AppType, limit int) ([]database.BlocklistLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocklistLog", ctx, appType, limit)
	ret0, _ := ret[0].([]database.BlocklistLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocklistLog indicates an expected call of GetBlocklistLog.
func (mr *MockStoreMockRecorder) GetBlocklistLog(ctx, appType, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocklistLog", reflect.TypeOf((*MockStore)(nil).GetBlocklistLog), ctx, appType, limit)
}

// GetBlocklistSource mocks base method.
func (m *MockStore) GetBlocklistSource(ctx context.Context, id uuid.UUID) (*database.BlocklistSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocklistSource", ctx, id)
	ret0, _ := ret[0].(*database.BlocklistSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocklistSource indicates an expected call of GetBlocklistSource.
func (mr *MockStoreMockRecorder) GetBlocklistSource(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocklistSource", reflect.TypeOf((*MockStore)(nil).GetBlocklistSource), ctx, id)
}

// GetDownloadClientSettings mocks base method.
func (m *MockStore) GetDownloadClientSettings(ctx context.Context, appType database.AppType) (*database.DownloadClientSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadClientSettings", ctx, appType)
	ret0, _ := ret[0].(*database.DownloadClientSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadClientSettings indicates an expected call of GetDownloadClientSettings.
func (mr *MockStoreMockRecorder) GetDownloadClientSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadClientSettings", reflect.TypeOf((*MockStore)(nil).GetDownloadClientSettings), ctx, appType)
}

// GetGeneralSettings mocks base method.
func (m *MockStore) GetGeneralSettings(ctx context.Context) (*database.GeneralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx)
	ret0, _ := ret[0].(*database.GeneralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockStoreMockRecorder) GetGeneralSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockStore)(nil).GetGeneralSettings), ctx)
}

// GetInstance mocks base method.
func (m *MockStore) GetInstance(ctx context.Context, id uuid.UUID) (*database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, id)
	ret0, _ := ret[0].(*database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockStoreMockRecorder) GetInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockStore)(nil).GetInstance), ctx, id)
}

// GetLastReset mocks base method.
func (m *MockStore) GetLastReset(ctx context.Context, appType database.AppType, instanceID uuid.UUID) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReset", ctx, appType, instanceID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReset indicates an expected call of GetLastReset.
func (mr *MockStoreMockRecorder) GetLastReset(ctx, appType, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReset", reflect.TypeOf((*MockStore)(nil).GetLastReset), ctx, appType, instanceID)
}

// GetNotificationProvider mocks base method.
func (m *MockStore) GetNotificationProvider(ctx context.Context, id uuid.UUID) (*database.NotificationProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationProvider", ctx, id)
	ret0, _ := ret[0].(*database.NotificationProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationProvider indicates an expected call of GetNotificationProvider.
func (mr *MockStoreMockRecorder) GetNotificationProvider(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationProvider", reflect.TypeOf((*MockStore)(nil).GetNotificationProvider), ctx, id)
}

// GetProwlarrSettings mocks base method.
func (m *MockStore) GetProwlarrSettings(ctx context.Context) (*database.ProwlarrSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProwlarrSettings", ctx)
	ret0, _ := ret[0].(*database.ProwlarrSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProwlarrSettings indicates an expected call of GetProwlarrSettings.
func (mr *MockStoreMockRecorder) GetProwlarrSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProwlarrSettings", reflect.TypeOf((*MockStore)(nil).GetProwlarrSettings), ctx)
}

// GetQueueCleanerSettings mocks base method.
func (m *MockStore) GetQueueCleanerSettings(ctx context.Context, appType database.AppType) (*database.QueueCleanerSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueCleanerSettings", ctx, appType)
	ret0, _ := ret[0].(*database.QueueCleanerSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueCleanerSettings indicates an expected call of GetQueueCleanerSettings.
func (mr *MockStoreMockRecorder) GetQueueCleanerSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueCleanerSettings", reflect.TypeOf((*MockStore)(nil).GetQueueCleanerSettings), ctx, appType)
}

// GetSABnzbdSettings mocks base method.
func (m *MockStore) GetSABnzbdSettings(ctx context.Context) (*database.SABnzbdSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSABnzbdSettings", ctx)
	ret0, _ := ret[0].(*database.SABnzbdSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSABnzbdSettings indicates an expected call of GetSABnzbdSettings.
func (mr *MockStoreMockRecorder) GetSABnzbdSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSABnzbdSettings", reflect.TypeOf((*MockStore)(nil).GetSABnzbdSettings), ctx)
}

// GetScoringProfile mocks base method.
func (m *MockStore) GetScoringProfile(ctx context.Context, appType database.AppType) (*database.ScoringProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScoringProfile", ctx, appType)
	ret0, _ := ret[0].(*database.ScoringProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScoringProfile indicates an expected call of GetScoringProfile.
func (mr *MockStoreMockRecorder) GetScoringProfile(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScoringProfile", reflect.TypeOf((*MockStore)(nil).GetScoringProfile), ctx, appType)
}

// GetSeerrSettings mocks base method.
func (m *MockStore) GetSeerrSettings(ctx context.Context) (*database.SeerrSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeerrSettings", ctx)
	ret0, _ := ret[0].(*database.SeerrSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeerrSettings indicates an expected call of GetSeerrSettings.
func (mr *MockStoreMockRecorder) GetSeerrSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeerrSettings", reflect.TypeOf((*MockStore)(nil).GetSeerrSettings), ctx)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(ctx context.Context, username string) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), ctx, username)
}

// ListBlocklistRules mocks base method.
func (m *MockStore) ListBlocklistRules(ctx context.Context) ([]database.BlocklistRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlocklistRules", ctx)
	ret0, _ := ret[0].([]database.BlocklistRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocklistRules indicates an expected call of ListBlocklistRules.
func (mr *MockStoreMockRecorder) ListBlocklistRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocklistRules", reflect.TypeOf((*MockStore)(nil).ListBlocklistRules), ctx)
}

// ListBlocklistSources mocks base method.
func (m *MockStore) ListBlocklistSources(ctx context.Context) ([]database.BlocklistSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlocklistSources", ctx)
	ret0, _ := ret[0].([]database.BlocklistSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocklistSources indicates an expected call of ListBlocklistSources.
func (mr *MockStoreMockRecorder) ListBlocklistSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocklistSources", reflect.TypeOf((*MockStore)(nil).ListBlocklistSources), ctx)
}

// ListEnabledBlocklistRules mocks base method.
func (m *MockStore) ListEnabledBlocklistRules(ctx context.Context) ([]database.BlocklistRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledBlocklistRules", ctx)
	ret0, _ := ret[0].([]database.BlocklistRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledBlocklistRules indicates an expected call of ListEnabledBlocklistRules.
func (mr *MockStoreMockRecorder) ListEnabledBlocklistRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledBlocklistRules", reflect.TypeOf((*MockStore)(nil).ListEnabledBlocklistRules), ctx)
}

// ListEnabledNotificationProviders mocks base method.
func (m *MockStore) ListEnabledNotificationProviders(ctx context.Context) ([]database.NotificationProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledNotificationProviders", ctx)
	ret0, _ := ret[0].([]database.NotificationProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledNotificationProviders indicates an expected call of ListEnabledNotificationProviders.
func (mr *MockStoreMockRecorder) ListEnabledNotificationProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledNotificationProviders", reflect.TypeOf((*MockStore)(nil).ListEnabledNotificationProviders), ctx)
}

// ListInstances mocks base method.
func (m *MockStore) ListInstances(ctx context.Context, appType database.AppType) ([]database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, appType)
	ret0, _ := ret[0].([]database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockStoreMockRecorder) ListInstances(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockStore)(nil).ListInstances), ctx, appType)
}

// ListLurkHistory mocks base method.
func (m *MockStore) ListLurkHistory(ctx context.Context, q database.HistoryQuery) ([]database.LurkHistory, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLurkHistory", ctx, q)
	ret0, _ := ret[0].([]database.LurkHistory)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLurkHistory indicates an expected call of ListLurkHistory.
func (mr *MockStoreMockRecorder) ListLurkHistory(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLurkHistory", reflect.TypeOf((*MockStore)(nil).ListLurkHistory), ctx, q)
}

// ListNotificationProviders mocks base method.
func (m *MockStore) ListNotificationProviders(ctx context.Context) ([]database.NotificationProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationProviders", ctx)
	ret0, _ := ret[0].([]database.NotificationProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationProviders indicates an expected call of ListNotificationProviders.
func (mr *MockStoreMockRecorder) ListNotificationProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationProviders", reflect.TypeOf((*MockStore)(nil).ListNotificationProviders), ctx)
}

// ListScheduleExecutions mocks base method.
func (m *MockStore) ListScheduleExecutions(ctx context.Context, limit int) ([]database.ScheduleExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduleExecutions", ctx, limit)
	ret0, _ := ret[0].([]database.ScheduleExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduleExecutions indicates an expected call of ListScheduleExecutions.
func (mr *MockStoreMockRecorder) ListScheduleExecutions(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduleExecutions", reflect.TypeOf((*MockStore)(nil).ListScheduleExecutions), ctx, limit)
}

// ListSchedules mocks base method.
func (m *MockStore) ListSchedules(ctx context.Context) ([]database.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx)
	ret0, _ := ret[0].([]database.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockStoreMockRecorder) ListSchedules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockStore)(nil).ListSchedules), ctx)
}

// QueryLogs mocks base method.
func (m *MockStore) QueryLogs(ctx context.Context, q database.LogQuery) ([]database.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryLogs", ctx, q)
	ret0, _ := ret[0].([]database.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryLogs indicates an expected call of QueryLogs.
func (mr *MockStoreMockRecorder) QueryLogs(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryLogs", reflect.TypeOf((*MockStore)(nil).QueryLogs), ctx, q)
}

// ResetState mocks base method.
func (m *MockStore) ResetState(ctx context.Context, appType database.AppType, instanceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetState", ctx, appType, instanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetState indicates an expected call of ResetState.
func (mr *MockStoreMockRecorder) ResetState(ctx, appType, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetState", reflect.TypeOf((*MockStore)(nil).ResetState), ctx, appType, instanceID)
}

// ResetStats mocks base method.
func (m *MockStore) ResetStats(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetStats", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetStats indicates an expected call of ResetStats.
func (mr *MockStoreMockRecorder) ResetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetStats", reflect.TypeOf((*MockStore)(nil).ResetStats), ctx)
}

// SetTOTPSecret mocks base method.
func (m *MockStore) SetTOTPSecret(ctx context.Context, id uuid.UUID, secret *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTOTPSecret", ctx, id, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTOTPSecret indicates an expected call of SetTOTPSecret.
func (mr *MockStoreMockRecorder) SetTOTPSecret(ctx, id, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTOTPSecret", reflect.TypeOf((*MockStore)(nil).SetTOTPSecret), ctx, id, secret)
}

// UpdateAppSettings mocks base method.
func (m *MockStore) UpdateAppSettings(ctx context.Context, s *database.AppSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppSettings indicates an expected call of UpdateAppSettings.
func (mr *MockStoreMockRecorder) UpdateAppSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppSettings", reflect.TypeOf((*MockStore)(nil).UpdateAppSettings), ctx, s)
}

// UpdateBlocklistSource mocks base method.
func (m *MockStore) UpdateBlocklistSource(ctx context.Context, s *database.BlocklistSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlocklistSource", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlocklistSource indicates an expected call of UpdateBlocklistSource.
func (mr *MockStoreMockRecorder) UpdateBlocklistSource(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlocklistSource", reflect.TypeOf((*MockStore)(nil).UpdateBlocklistSource), ctx, s)
}

// UpdateBlocklistSourceSync mocks base method.
func (m *MockStore) UpdateBlocklistSourceSync(ctx context.Context, id uuid.UUID, etag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlocklistSourceSync", ctx, id, etag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlocklistSourceSync indicates an expected call of UpdateBlocklistSourceSync.
func (mr *MockStoreMockRecorder) UpdateBlocklistSourceSync(ctx, id, etag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlocklistSourceSync", reflect.TypeOf((*MockStore)(nil).UpdateBlocklistSourceSync), ctx, id, etag)
}

// UpdateDownloadClientSettings mocks base method.
func (m *MockStore) UpdateDownloadClientSettings(ctx context.Context, s *database.DownloadClientSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDownloadClientSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDownloadClientSettings indicates an expected call of UpdateDownloadClientSettings.
func (mr *MockStoreMockRecorder) UpdateDownloadClientSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDownloadClientSettings", reflect.TypeOf((*MockStore)(nil).UpdateDownloadClientSettings), ctx, s)
}

// UpdateInstance mocks base method.
func (m *MockStore) UpdateInstance(ctx context.Context, id uuid.UUID, name, apiURL, apiKey string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", ctx, id, name, apiURL, apiKey, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockStoreMockRecorder) UpdateInstance(ctx, id, name, apiURL, apiKey, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockStore)(nil).UpdateInstance), ctx, id, name, apiURL, apiKey, enabled)
}

// UpdateNotificationProvider mocks base method.
func (m *MockStore) UpdateNotificationProvider(ctx context.Context, p *database.NotificationProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationProvider", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationProvider indicates an expected call of UpdateNotificationProvider.
func (mr *MockStoreMockRecorder) UpdateNotificationProvider(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationProvider", reflect.TypeOf((*MockStore)(nil).UpdateNotificationProvider), ctx, p)
}

// UpdatePassword mocks base method.
func (m *MockStore) UpdatePassword(ctx context.Context, id uuid.UUID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockStoreMockRecorder) UpdatePassword(ctx, id, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockStore)(nil).UpdatePassword), ctx, id, passwordHash)
}

// UpdateProwlarrSettings mocks base method.
func (m *MockStore) UpdateProwlarrSettings(ctx context.Context, s *database.ProwlarrSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProwlarrSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProwlarrSettings indicates an expected call of UpdateProwlarrSettings.
func (mr *MockStoreMockRecorder) UpdateProwlarrSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProwlarrSettings", reflect.TypeOf((*MockStore)(nil).UpdateProwlarrSettings), ctx, s)
}

// UpdateQueueCleanerSettings mocks base method.
func (m *MockStore) UpdateQueueCleanerSettings(ctx context.Context, s *database.QueueCleanerSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQueueCleanerSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQueueCleanerSettings indicates an expected call of UpdateQueueCleanerSettings.
func (mr *MockStoreMockRecorder) UpdateQueueCleanerSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQueueCleanerSettings", reflect.TypeOf((*MockStore)(nil).UpdateQueueCleanerSettings), ctx, s)
}

// UpdateSABnzbdSettings mocks base method.
func (m *MockStore) UpdateSABnzbdSettings(ctx context.Context, s *database.SABnzbdSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSABnzbdSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSABnzbdSettings indicates an expected call of UpdateSABnzbdSettings.
func (mr *MockStoreMockRecorder) UpdateSABnzbdSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSABnzbdSettings", reflect.TypeOf((*MockStore)(nil).UpdateSABnzbdSettings), ctx, s)
}

// UpdateSchedule mocks base method.
func (m *MockStore) UpdateSchedule(ctx context.Context, s *database.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockStoreMockRecorder) UpdateSchedule(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockStore)(nil).UpdateSchedule), ctx, s)
}

// UpdateScoringProfile mocks base method.
func (m *MockStore) UpdateScoringProfile(ctx context.Context, p *database.ScoringProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScoringProfile", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScoringProfile indicates an expected call of UpdateScoringProfile.
func (mr *MockStoreMockRecorder) UpdateScoringProfile(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScoringProfile", reflect.TypeOf((*MockStore)(nil).UpdateScoringProfile), ctx, p)
}

// UpdateSeerrSettings mocks base method.
func (m *MockStore) UpdateSeerrSettings(ctx context.Context, s *database.SeerrSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeerrSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSeerrSettings indicates an expected call of UpdateSeerrSettings.
func (mr *MockStoreMockRecorder) UpdateSeerrSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeerrSettings", reflect.TypeOf((*MockStore)(nil).UpdateSeerrSettings), ctx, s)
}

// UpdateUsername mocks base method.
func (m *MockStore) UpdateUsername(ctx context.Context, id uuid.UUID, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", ctx, id, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername.
func (mr *MockStoreMockRecorder) UpdateUsername(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*MockStore)(nil).UpdateUsername), ctx, id, username)
}

// UpsertGeneralSettings mocks base method.
func (m *MockStore) UpsertGeneralSettings(ctx context.Context, s *database.GeneralSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGeneralSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGeneralSettings indicates an expected call of UpsertGeneralSettings.
func (mr *MockStoreMockRecorder) UpsertGeneralSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGeneralSettings", reflect.TypeOf((*MockStore)(nil).UpsertGeneralSettings), ctx, s)
}

// UserCount mocks base method.
func (m *MockStore) UserCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserCount indicates an expected call of UserCount.
func (mr *MockStoreMockRecorder) UserCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCount", reflect.TypeOf((*MockStore)(nil).UserCount), ctx)
}
