// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/api (interfaces: WebAuthnProvider)
//
// Generated by this command:
//
//	mockgen -destination=mock_webauthn_test.go -package=api github.com/lusoris/lurkarr/internal/api WebAuthnProvider
//

// Package api is a generated GoMock package.
package api

import (
	http "net/http"
	reflect "reflect"

	protocol "github.com/go-webauthn/webauthn/protocol"
	webauthn "github.com/go-webauthn/webauthn/webauthn"
	gomock "go.uber.org/mock/gomock"
)

// MockWebAuthnProvider is a mock of WebAuthnProvider interface.
type MockWebAuthnProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnProviderMockRecorder
	isgomock struct{}
}

// MockWebAuthnProviderMockRecorder is the mock recorder for MockWebAuthnProvider.
type MockWebAuthnProviderMockRecorder struct {
	mock *MockWebAuthnProvider
}

// NewMockWebAuthnProvider creates a new mock instance.
func NewMockWebAuthnProvider(ctrl *gomock.Controller) *MockWebAuthnProvider {
	mock := &MockWebAuthnProvider{ctrl: ctrl}
	mock.recorder = &MockWebAuthnProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthnProvider) EXPECT() *MockWebAuthnProviderMockRecorder {
	return m.recorder
}

// BeginDiscoverableLogin mocks base method.
func (m *MockWebAuthnProvider) BeginDiscoverableLogin(opts ...webauthn.LoginOption) (*protocol.CredentialAssertion, *webauthn.SessionData, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeginDiscoverableLogin", varargs...)
	ret0, _ := ret[0].(*protocol.CredentialAssertion)
	ret1, _ := ret[1].(*webauthn.SessionData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginDiscoverableLogin indicates an expected call of BeginDiscoverableLogin.
func (mr *MockWebAuthnProviderMockRecorder) BeginDiscoverableLogin(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginDiscoverableLogin", reflect.TypeOf((*MockWebAuthnProvider)(nil).BeginDiscoverableLogin), opts...)
}

// BeginRegistration mocks base method.
func (m *MockWebAuthnProvider) BeginRegistration(user webauthn.User, opts ...webauthn.RegistrationOption) (*protocol.CredentialCreation, *webauthn.SessionData, error) {
	m.ctrl.T.Helper()
	varargs := []any{user}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeginRegistration", varargs...)
	ret0, _ := ret[0].(*protocol.CredentialCreation)
	ret1, _ := ret[1].(*webauthn.SessionData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginRegistration indicates an expected call of BeginRegistration.
func (mr *MockWebAuthnProviderMockRecorder) BeginRegistration(user any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRegistration", reflect.TypeOf((*MockWebAuthnProvider)(nil).BeginRegistration), varargs...)
}

// FinishRegistration mocks base method.
func (m *MockWebAuthnProvider) FinishRegistration(user webauthn.User, session webauthn.SessionData, r *http.Request) (*webauthn.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishRegistration", user, session, r)
	ret0, _ := ret[0].(*webauthn.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishRegistration indicates an expected call of FinishRegistration.
func (mr *MockWebAuthnProviderMockRecorder) FinishRegistration(user, session, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishRegistration", reflect.TypeOf((*MockWebAuthnProvider)(nil).FinishRegistration), user, session, r)
}

// ValidatePasskeyLogin mocks base method.
func (m *MockWebAuthnProvider) ValidatePasskeyLogin(handler webauthn.DiscoverableUserHandler, session webauthn.SessionData, parsedResponse *protocol.ParsedCredentialAssertionData) (webauthn.User, *webauthn.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePasskeyLogin", handler, session, parsedResponse)
	ret0, _ := ret[0].(webauthn.User)
	ret1, _ := ret[1].(*webauthn.Credential)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidatePasskeyLogin indicates an expected call of ValidatePasskeyLogin.
func (mr *MockWebAuthnProviderMockRecorder) ValidatePasskeyLogin(handler, session, parsedResponse any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePasskeyLogin", reflect.TypeOf((*MockWebAuthnProvider)(nil).ValidatePasskeyLogin), handler, session, parsedResponse)
}
