// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/api (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=api github.com/lusoris/lurkarr/internal/api Store
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateBlocklistRule mocks base method.
func (m *MockStore) CreateBlocklistRule(ctx context.Context, r *database.BlocklistRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlocklistRule", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlocklistRule indicates an expected call of CreateBlocklistRule.
func (mr *MockStoreMockRecorder) CreateBlocklistRule(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlocklistRule", reflect.TypeOf((*MockStore)(nil).CreateBlocklistRule), ctx, r)
}

// CreateBlocklistSource mocks base method.
func (m *MockStore) CreateBlocklistSource(ctx context.Context, s *database.BlocklistSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlocklistSource", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlocklistSource indicates an expected call of CreateBlocklistSource.
func (mr *MockStoreMockRecorder) CreateBlocklistSource(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlocklistSource", reflect.TypeOf((*MockStore)(nil).CreateBlocklistSource), ctx, s)
}

// CreateDownloadClientInstance mocks base method.
func (m *MockStore) CreateDownloadClientInstance(ctx context.Context, d *database.DownloadClientInstance) (*database.DownloadClientInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDownloadClientInstance", ctx, d)
	ret0, _ := ret[0].(*database.DownloadClientInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDownloadClientInstance indicates an expected call of CreateDownloadClientInstance.
func (mr *MockStoreMockRecorder) CreateDownloadClientInstance(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDownloadClientInstance", reflect.TypeOf((*MockStore)(nil).CreateDownloadClientInstance), ctx, d)
}

// CreateInstance mocks base method.
func (m *MockStore) CreateInstance(ctx context.Context, appType database.AppType, name, apiURL, apiKey string) (*database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, appType, name, apiURL, apiKey)
	ret0, _ := ret[0].(*database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockStoreMockRecorder) CreateInstance(ctx, appType, name, apiURL, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockStore)(nil).CreateInstance), ctx, appType, name, apiURL, apiKey)
}

// CreateInstanceGroup mocks base method.
func (m *MockStore) CreateInstanceGroup(ctx context.Context, appType database.AppType, name string) (*database.InstanceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstanceGroup", ctx, appType, name)
	ret0, _ := ret[0].(*database.InstanceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstanceGroup indicates an expected call of CreateInstanceGroup.
func (mr *MockStoreMockRecorder) CreateInstanceGroup(ctx, appType, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceGroup", reflect.TypeOf((*MockStore)(nil).CreateInstanceGroup), ctx, appType, name)
}

// CreateNotificationProvider mocks base method.
func (m *MockStore) CreateNotificationProvider(ctx context.Context, p *database.NotificationProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationProvider", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotificationProvider indicates an expected call of CreateNotificationProvider.
func (mr *MockStoreMockRecorder) CreateNotificationProvider(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationProvider", reflect.TypeOf((*MockStore)(nil).CreateNotificationProvider), ctx, p)
}

// CreateSchedule mocks base method.
func (m *MockStore) CreateSchedule(ctx context.Context, s *database.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockStoreMockRecorder) CreateSchedule(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockStore)(nil).CreateSchedule), ctx, s)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, username, passwordHash string) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, passwordHash)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, username, passwordHash)
}

// CreateWebAuthnCredential mocks base method.
func (m *MockStore) CreateWebAuthnCredential(ctx context.Context, c *database.WebAuthnCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebAuthnCredential", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWebAuthnCredential indicates an expected call of CreateWebAuthnCredential.
func (mr *MockStoreMockRecorder) CreateWebAuthnCredential(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebAuthnCredential", reflect.TypeOf((*MockStore)(nil).CreateWebAuthnCredential), ctx, c)
}

// DeleteBlocklistRule mocks base method.
func (m *MockStore) DeleteBlocklistRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlocklistRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlocklistRule indicates an expected call of DeleteBlocklistRule.
func (mr *MockStoreMockRecorder) DeleteBlocklistRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlocklistRule", reflect.TypeOf((*MockStore)(nil).DeleteBlocklistRule), ctx, id)
}

// DeleteBlocklistRulesBySource mocks base method.
func (m *MockStore) DeleteBlocklistRulesBySource(ctx context.Context, sourceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlocklistRulesBySource", ctx, sourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlocklistRulesBySource indicates an expected call of DeleteBlocklistRulesBySource.
func (mr *MockStoreMockRecorder) DeleteBlocklistRulesBySource(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlocklistRulesBySource", reflect.TypeOf((*MockStore)(nil).DeleteBlocklistRulesBySource), ctx, sourceID)
}

// DeleteBlocklistSource mocks base method.
func (m *MockStore) DeleteBlocklistSource(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlocklistSource", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlocklistSource indicates an expected call of DeleteBlocklistSource.
func (mr *MockStoreMockRecorder) DeleteBlocklistSource(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlocklistSource", reflect.TypeOf((*MockStore)(nil).DeleteBlocklistSource), ctx, id)
}

// DeleteDownloadClientInstance mocks base method.
func (m *MockStore) DeleteDownloadClientInstance(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDownloadClientInstance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDownloadClientInstance indicates an expected call of DeleteDownloadClientInstance.
func (mr *MockStoreMockRecorder) DeleteDownloadClientInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDownloadClientInstance", reflect.TypeOf((*MockStore)(nil).DeleteDownloadClientInstance), ctx, id)
}

// DeleteHistory mocks base method.
func (m *MockStore) DeleteHistory(ctx context.Context, appType database.AppType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHistory", ctx, appType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHistory indicates an expected call of DeleteHistory.
func (mr *MockStoreMockRecorder) DeleteHistory(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHistory", reflect.TypeOf((*MockStore)(nil).DeleteHistory), ctx, appType)
}

// DeleteInstance mocks base method.
func (m *MockStore) DeleteInstance(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockStoreMockRecorder) DeleteInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockStore)(nil).DeleteInstance), ctx, id)
}

// DeleteInstanceGroup mocks base method.
func (m *MockStore) DeleteInstanceGroup(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstanceGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstanceGroup indicates an expected call of DeleteInstanceGroup.
func (mr *MockStoreMockRecorder) DeleteInstanceGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceGroup", reflect.TypeOf((*MockStore)(nil).DeleteInstanceGroup), ctx, id)
}

// DeleteNotificationProvider mocks base method.
func (m *MockStore) DeleteNotificationProvider(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotificationProvider", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotificationProvider indicates an expected call of DeleteNotificationProvider.
func (mr *MockStoreMockRecorder) DeleteNotificationProvider(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotificationProvider", reflect.TypeOf((*MockStore)(nil).DeleteNotificationProvider), ctx, id)
}

// DeleteSchedule mocks base method.
func (m *MockStore) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockStoreMockRecorder) DeleteSchedule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockStore)(nil).DeleteSchedule), ctx, id)
}

// DeleteSession mocks base method.
func (m *MockStore) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStoreMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStore)(nil).DeleteSession), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, id)
}

// DeleteUserSessions mocks base method.
func (m *MockStore) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSessions indicates an expected call of DeleteUserSessions.
func (mr *MockStoreMockRecorder) DeleteUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSessions", reflect.TypeOf((*MockStore)(nil).DeleteUserSessions), ctx, userID)
}

// DeleteUserSessionsExcept mocks base method.
func (m *MockStore) DeleteUserSessionsExcept(ctx context.Context, userID, keep uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSessionsExcept", ctx, userID, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSessionsExcept indicates an expected call of DeleteUserSessionsExcept.
func (mr *MockStoreMockRecorder) DeleteUserSessionsExcept(ctx, userID, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSessionsExcept", reflect.TypeOf((*MockStore)(nil).DeleteUserSessionsExcept), ctx, userID, keep)
}

// DeleteWebAuthnCredential mocks base method.
func (m *MockStore) DeleteWebAuthnCredential(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebAuthnCredential", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebAuthnCredential indicates an expected call of DeleteWebAuthnCredential.
func (mr *MockStoreMockRecorder) DeleteWebAuthnCredential(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebAuthnCredential", reflect.TypeOf((*MockStore)(nil).DeleteWebAuthnCredential), ctx, id)
}

// GetAllHourlyCaps mocks base method.
func (m *MockStore) GetAllHourlyCaps(ctx context.Context) ([]database.HourlyCap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHourlyCaps", ctx)
	ret0, _ := ret[0].([]database.HourlyCap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHourlyCaps indicates an expected call of GetAllHourlyCaps.
func (mr *MockStoreMockRecorder) GetAllHourlyCaps(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHourlyCaps", reflect.TypeOf((*MockStore)(nil).GetAllHourlyCaps), ctx)
}

// GetAllStats mocks base method.
func (m *MockStore) GetAllStats(ctx context.Context) ([]database.LurkStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStats", ctx)
	ret0, _ := ret[0].([]database.LurkStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStats indicates an expected call of GetAllStats.
func (mr *MockStoreMockRecorder) GetAllStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStats", reflect.TypeOf((*MockStore)(nil).GetAllStats), ctx)
}

// GetAppSettings mocks base method.
func (m *MockStore) GetAppSettings(ctx context.Context, appType database.AppType) (*database.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSettings", ctx, appType)
	ret0, _ := ret[0].(*database.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSettings indicates an expected call of GetAppSettings.
func (mr *MockStoreMockRecorder) GetAppSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSettings", reflect.TypeOf((*MockStore)(nil).GetAppSettings), ctx, appType)
}

// GetAutoImportLog mocks base method.
func (m *MockStore) GetAutoImportLog(ctx context.Context, appType database.AppType, limit int) ([]database.AutoImportLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoImportLog", ctx, appType, limit)
	ret0, _ := ret[0].([]database.AutoImportLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoImportLog indicates an expected call of GetAutoImportLog.
func (mr *MockStoreMockRecorder) GetAutoImportLog(ctx, appType, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoImportLog", reflect.TypeOf((*MockStore)(nil).GetAutoImportLog), ctx, appType, limit)
}

// GetBlocklistLog mocks base method.
func (m *MockStore) GetBlocklistLog(ctx context.Context, appType database.AppType, limit int) ([]database.BlocklistLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocklistLog", ctx, appType, limit)
	ret0, _ := ret[0].([]database.BlocklistLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocklistLog indicates an expected call of GetBlocklistLog.
func (mr *MockStoreMockRecorder) GetBlocklistLog(ctx, appType, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocklistLog", reflect.TypeOf((*MockStore)(nil).GetBlocklistLog), ctx, appType, limit)
}

// GetBlocklistSource mocks base method.
func (m *MockStore) GetBlocklistSource(ctx context.Context, id uuid.UUID) (*database.BlocklistSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocklistSource", ctx, id)
	ret0, _ := ret[0].(*database.BlocklistSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocklistSource indicates an expected call of GetBlocklistSource.
func (mr *MockStoreMockRecorder) GetBlocklistSource(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocklistSource", reflect.TypeOf((*MockStore)(nil).GetBlocklistSource), ctx, id)
}

// GetDownloadClientInstance mocks base method.
func (m *MockStore) GetDownloadClientInstance(ctx context.Context, id uuid.UUID) (*database.DownloadClientInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadClientInstance", ctx, id)
	ret0, _ := ret[0].(*database.DownloadClientInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadClientInstance indicates an expected call of GetDownloadClientInstance.
func (mr *MockStoreMockRecorder) GetDownloadClientInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadClientInstance", reflect.TypeOf((*MockStore)(nil).GetDownloadClientInstance), ctx, id)
}

// GetDownloadClientSettings mocks base method.
func (m *MockStore) GetDownloadClientSettings(ctx context.Context, appType database.AppType) (*database.DownloadClientSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadClientSettings", ctx, appType)
	ret0, _ := ret[0].(*database.DownloadClientSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadClientSettings indicates an expected call of GetDownloadClientSettings.
func (mr *MockStoreMockRecorder) GetDownloadClientSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadClientSettings", reflect.TypeOf((*MockStore)(nil).GetDownloadClientSettings), ctx, appType)
}

// GetGeneralSettings mocks base method.
func (m *MockStore) GetGeneralSettings(ctx context.Context) (*database.GeneralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx)
	ret0, _ := ret[0].(*database.GeneralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockStoreMockRecorder) GetGeneralSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockStore)(nil).GetGeneralSettings), ctx)
}

// GetInstance mocks base method.
func (m *MockStore) GetInstance(ctx context.Context, id uuid.UUID) (*database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, id)
	ret0, _ := ret[0].(*database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockStoreMockRecorder) GetInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockStore)(nil).GetInstance), ctx, id)
}

// GetInstanceGroup mocks base method.
func (m *MockStore) GetInstanceGroup(ctx context.Context, id uuid.UUID) (*database.InstanceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceGroup", ctx, id)
	ret0, _ := ret[0].(*database.InstanceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceGroup indicates an expected call of GetInstanceGroup.
func (mr *MockStoreMockRecorder) GetInstanceGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceGroup", reflect.TypeOf((*MockStore)(nil).GetInstanceGroup), ctx, id)
}

// GetInstanceGroupForInstance mocks base method.
func (m *MockStore) GetInstanceGroupForInstance(ctx context.Context, instanceID uuid.UUID) (*database.InstanceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceGroupForInstance", ctx, instanceID)
	ret0, _ := ret[0].(*database.InstanceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceGroupForInstance indicates an expected call of GetInstanceGroupForInstance.
func (mr *MockStoreMockRecorder) GetInstanceGroupForInstance(ctx, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceGroupForInstance", reflect.TypeOf((*MockStore)(nil).GetInstanceGroupForInstance), ctx, instanceID)
}

// GetLastReset mocks base method.
func (m *MockStore) GetLastReset(ctx context.Context, appType database.AppType, instanceID uuid.UUID) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReset", ctx, appType, instanceID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReset indicates an expected call of GetLastReset.
func (mr *MockStoreMockRecorder) GetLastReset(ctx, appType, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReset", reflect.TypeOf((*MockStore)(nil).GetLastReset), ctx, appType, instanceID)
}

// GetNotificationProvider mocks base method.
func (m *MockStore) GetNotificationProvider(ctx context.Context, id uuid.UUID) (*database.NotificationProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationProvider", ctx, id)
	ret0, _ := ret[0].(*database.NotificationProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationProvider indicates an expected call of GetNotificationProvider.
func (mr *MockStoreMockRecorder) GetNotificationProvider(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationProvider", reflect.TypeOf((*MockStore)(nil).GetNotificationProvider), ctx, id)
}

// GetOIDCSettings mocks base method.
func (m *MockStore) GetOIDCSettings(ctx context.Context) (*database.OIDCSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOIDCSettings", ctx)
	ret0, _ := ret[0].(*database.OIDCSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOIDCSettings indicates an expected call of GetOIDCSettings.
func (mr *MockStoreMockRecorder) GetOIDCSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOIDCSettings", reflect.TypeOf((*MockStore)(nil).GetOIDCSettings), ctx)
}

// GetProwlarrSettings mocks base method.
func (m *MockStore) GetProwlarrSettings(ctx context.Context) (*database.ProwlarrSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProwlarrSettings", ctx)
	ret0, _ := ret[0].(*database.ProwlarrSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProwlarrSettings indicates an expected call of GetProwlarrSettings.
func (mr *MockStoreMockRecorder) GetProwlarrSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProwlarrSettings", reflect.TypeOf((*MockStore)(nil).GetProwlarrSettings), ctx)
}

// GetQueueCleanerSettings mocks base method.
func (m *MockStore) GetQueueCleanerSettings(ctx context.Context, appType database.AppType) (*database.QueueCleanerSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueCleanerSettings", ctx, appType)
	ret0, _ := ret[0].(*database.QueueCleanerSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueCleanerSettings indicates an expected call of GetQueueCleanerSettings.
func (mr *MockStoreMockRecorder) GetQueueCleanerSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueCleanerSettings", reflect.TypeOf((*MockStore)(nil).GetQueueCleanerSettings), ctx, appType)
}

// GetSABnzbdSettings mocks base method.
func (m *MockStore) GetSABnzbdSettings(ctx context.Context) (*database.SABnzbdSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSABnzbdSettings", ctx)
	ret0, _ := ret[0].(*database.SABnzbdSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSABnzbdSettings indicates an expected call of GetSABnzbdSettings.
func (mr *MockStoreMockRecorder) GetSABnzbdSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSABnzbdSettings", reflect.TypeOf((*MockStore)(nil).GetSABnzbdSettings), ctx)
}

// GetScoringProfile mocks base method.
func (m *MockStore) GetScoringProfile(ctx context.Context, appType database.AppType) (*database.ScoringProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScoringProfile", ctx, appType)
	ret0, _ := ret[0].(*database.ScoringProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScoringProfile indicates an expected call of GetScoringProfile.
func (mr *MockStoreMockRecorder) GetScoringProfile(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScoringProfile", reflect.TypeOf((*MockStore)(nil).GetScoringProfile), ctx, appType)
}

// GetSeerrSettings mocks base method.
func (m *MockStore) GetSeerrSettings(ctx context.Context) (*database.SeerrSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeerrSettings", ctx)
	ret0, _ := ret[0].(*database.SeerrSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeerrSettings indicates an expected call of GetSeerrSettings.
func (mr *MockStoreMockRecorder) GetSeerrSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeerrSettings", reflect.TypeOf((*MockStore)(nil).GetSeerrSettings), ctx)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(ctx context.Context, id uuid.UUID) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(ctx context.Context, username string) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), ctx, username)
}

// GetWebAuthnCredentialByID mocks base method.
func (m *MockStore) GetWebAuthnCredentialByID(ctx context.Context, credID []byte) (*database.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebAuthnCredentialByID", ctx, credID)
	ret0, _ := ret[0].(*database.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebAuthnCredentialByID indicates an expected call of GetWebAuthnCredentialByID.
func (mr *MockStoreMockRecorder) GetWebAuthnCredentialByID(ctx, credID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebAuthnCredentialByID", reflect.TypeOf((*MockStore)(nil).GetWebAuthnCredentialByID), ctx, credID)
}

// ListBlocklistRules mocks base method.
func (m *MockStore) ListBlocklistRules(ctx context.Context) ([]database.BlocklistRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlocklistRules", ctx)
	ret0, _ := ret[0].([]database.BlocklistRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocklistRules indicates an expected call of ListBlocklistRules.
func (mr *MockStoreMockRecorder) ListBlocklistRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocklistRules", reflect.TypeOf((*MockStore)(nil).ListBlocklistRules), ctx)
}

// ListBlocklistSources mocks base method.
func (m *MockStore) ListBlocklistSources(ctx context.Context) ([]database.BlocklistSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlocklistSources", ctx)
	ret0, _ := ret[0].([]database.BlocklistSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocklistSources indicates an expected call of ListBlocklistSources.
func (mr *MockStoreMockRecorder) ListBlocklistSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocklistSources", reflect.TypeOf((*MockStore)(nil).ListBlocklistSources), ctx)
}

// ListCrossInstanceMedia mocks base method.
func (m *MockStore) ListCrossInstanceMedia(ctx context.Context, groupID uuid.UUID) ([]database.CrossInstanceMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCrossInstanceMedia", ctx, groupID)
	ret0, _ := ret[0].([]database.CrossInstanceMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCrossInstanceMedia indicates an expected call of ListCrossInstanceMedia.
func (mr *MockStoreMockRecorder) ListCrossInstanceMedia(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCrossInstanceMedia", reflect.TypeOf((*MockStore)(nil).ListCrossInstanceMedia), ctx, groupID)
}

// ListDownloadClientInstances mocks base method.
func (m *MockStore) ListDownloadClientInstances(ctx context.Context) ([]database.DownloadClientInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDownloadClientInstances", ctx)
	ret0, _ := ret[0].([]database.DownloadClientInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDownloadClientInstances indicates an expected call of ListDownloadClientInstances.
func (mr *MockStoreMockRecorder) ListDownloadClientInstances(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDownloadClientInstances", reflect.TypeOf((*MockStore)(nil).ListDownloadClientInstances), ctx)
}

// ListEnabledDownloadClientInstances mocks base method.
func (m *MockStore) ListEnabledDownloadClientInstances(ctx context.Context) ([]database.DownloadClientInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledDownloadClientInstances", ctx)
	ret0, _ := ret[0].([]database.DownloadClientInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledDownloadClientInstances indicates an expected call of ListEnabledDownloadClientInstances.
func (mr *MockStoreMockRecorder) ListEnabledDownloadClientInstances(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledDownloadClientInstances", reflect.TypeOf((*MockStore)(nil).ListEnabledDownloadClientInstances), ctx)
}

// ListEnabledNotificationProviders mocks base method.
func (m *MockStore) ListEnabledNotificationProviders(ctx context.Context) ([]database.NotificationProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledNotificationProviders", ctx)
	ret0, _ := ret[0].([]database.NotificationProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledNotificationProviders indicates an expected call of ListEnabledNotificationProviders.
func (mr *MockStoreMockRecorder) ListEnabledNotificationProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledNotificationProviders", reflect.TypeOf((*MockStore)(nil).ListEnabledNotificationProviders), ctx)
}

// ListInstanceGroups mocks base method.
func (m *MockStore) ListInstanceGroups(ctx context.Context, appType database.AppType) ([]database.InstanceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceGroups", ctx, appType)
	ret0, _ := ret[0].([]database.InstanceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceGroups indicates an expected call of ListInstanceGroups.
func (mr *MockStoreMockRecorder) ListInstanceGroups(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceGroups", reflect.TypeOf((*MockStore)(nil).ListInstanceGroups), ctx, appType)
}

// ListInstances mocks base method.
func (m *MockStore) ListInstances(ctx context.Context, appType database.AppType) ([]database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, appType)
	ret0, _ := ret[0].([]database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockStoreMockRecorder) ListInstances(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockStore)(nil).ListInstances), ctx, appType)
}

// ListLurkHistory mocks base method.
func (m *MockStore) ListLurkHistory(ctx context.Context, q database.HistoryQuery) ([]database.LurkHistory, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLurkHistory", ctx, q)
	ret0, _ := ret[0].([]database.LurkHistory)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLurkHistory indicates an expected call of ListLurkHistory.
func (mr *MockStoreMockRecorder) ListLurkHistory(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLurkHistory", reflect.TypeOf((*MockStore)(nil).ListLurkHistory), ctx, q)
}

// ListNotificationProviders mocks base method.
func (m *MockStore) ListNotificationProviders(ctx context.Context) ([]database.NotificationProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationProviders", ctx)
	ret0, _ := ret[0].([]database.NotificationProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationProviders indicates an expected call of ListNotificationProviders.
func (mr *MockStoreMockRecorder) ListNotificationProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationProviders", reflect.TypeOf((*MockStore)(nil).ListNotificationProviders), ctx)
}

// ListScheduleExecutions mocks base method.
func (m *MockStore) ListScheduleExecutions(ctx context.Context, limit int) ([]database.ScheduleExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduleExecutions", ctx, limit)
	ret0, _ := ret[0].([]database.ScheduleExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduleExecutions indicates an expected call of ListScheduleExecutions.
func (mr *MockStoreMockRecorder) ListScheduleExecutions(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduleExecutions", reflect.TypeOf((*MockStore)(nil).ListScheduleExecutions), ctx, limit)
}

// ListSchedules mocks base method.
func (m *MockStore) ListSchedules(ctx context.Context) ([]database.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx)
	ret0, _ := ret[0].([]database.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockStoreMockRecorder) ListSchedules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockStore)(nil).ListSchedules), ctx)
}

// ListUserSessions mocks base method.
func (m *MockStore) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]database.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserSessions", ctx, userID)
	ret0, _ := ret[0].([]database.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserSessions indicates an expected call of ListUserSessions.
func (mr *MockStoreMockRecorder) ListUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserSessions", reflect.TypeOf((*MockStore)(nil).ListUserSessions), ctx, userID)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context) ([]database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx)
}

// ListWebAuthnCredentials mocks base method.
func (m *MockStore) ListWebAuthnCredentials(ctx context.Context, userID uuid.UUID) ([]database.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebAuthnCredentials", ctx, userID)
	ret0, _ := ret[0].([]database.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebAuthnCredentials indicates an expected call of ListWebAuthnCredentials.
func (mr *MockStoreMockRecorder) ListWebAuthnCredentials(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebAuthnCredentials", reflect.TypeOf((*MockStore)(nil).ListWebAuthnCredentials), ctx, userID)
}

// RenameWebAuthnCredential mocks base method.
func (m *MockStore) RenameWebAuthnCredential(ctx context.Context, id uuid.UUID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameWebAuthnCredential", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameWebAuthnCredential indicates an expected call of RenameWebAuthnCredential.
func (mr *MockStoreMockRecorder) RenameWebAuthnCredential(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameWebAuthnCredential", reflect.TypeOf((*MockStore)(nil).RenameWebAuthnCredential), ctx, id, name)
}

// ResetState mocks base method.
func (m *MockStore) ResetState(ctx context.Context, appType database.AppType, instanceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetState", ctx, appType, instanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetState indicates an expected call of ResetState.
func (mr *MockStoreMockRecorder) ResetState(ctx, appType, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetState", reflect.TypeOf((*MockStore)(nil).ResetState), ctx, appType, instanceID)
}

// ResetStats mocks base method.
func (m *MockStore) ResetStats(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetStats", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetStats indicates an expected call of ResetStats.
func (mr *MockStoreMockRecorder) ResetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetStats", reflect.TypeOf((*MockStore)(nil).ResetStats), ctx)
}

// SetGroupMembers mocks base method.
func (m *MockStore) SetGroupMembers(ctx context.Context, groupID uuid.UUID, members []database.InstanceGroupMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGroupMembers", ctx, groupID, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGroupMembers indicates an expected call of SetGroupMembers.
func (mr *MockStoreMockRecorder) SetGroupMembers(ctx, groupID, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGroupMembers", reflect.TypeOf((*MockStore)(nil).SetGroupMembers), ctx, groupID, members)
}

// SetRecoveryCodes mocks base method.
func (m *MockStore) SetRecoveryCodes(ctx context.Context, id uuid.UUID, codes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRecoveryCodes", ctx, id, codes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRecoveryCodes indicates an expected call of SetRecoveryCodes.
func (mr *MockStoreMockRecorder) SetRecoveryCodes(ctx, id, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRecoveryCodes", reflect.TypeOf((*MockStore)(nil).SetRecoveryCodes), ctx, id, codes)
}

// SetTOTPSecret mocks base method.
func (m *MockStore) SetTOTPSecret(ctx context.Context, id uuid.UUID, secret *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTOTPSecret", ctx, id, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTOTPSecret indicates an expected call of SetTOTPSecret.
func (mr *MockStoreMockRecorder) SetTOTPSecret(ctx, id, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTOTPSecret", reflect.TypeOf((*MockStore)(nil).SetTOTPSecret), ctx, id, secret)
}

// UpdateAppSettings mocks base method.
func (m *MockStore) UpdateAppSettings(ctx context.Context, s *database.AppSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppSettings indicates an expected call of UpdateAppSettings.
func (mr *MockStoreMockRecorder) UpdateAppSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppSettings", reflect.TypeOf((*MockStore)(nil).UpdateAppSettings), ctx, s)
}

// UpdateBlocklistSource mocks base method.
func (m *MockStore) UpdateBlocklistSource(ctx context.Context, s *database.BlocklistSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlocklistSource", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlocklistSource indicates an expected call of UpdateBlocklistSource.
func (mr *MockStoreMockRecorder) UpdateBlocklistSource(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlocklistSource", reflect.TypeOf((*MockStore)(nil).UpdateBlocklistSource), ctx, s)
}

// UpdateDownloadClientInstance mocks base method.
func (m *MockStore) UpdateDownloadClientInstance(ctx context.Context, d *database.DownloadClientInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDownloadClientInstance", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDownloadClientInstance indicates an expected call of UpdateDownloadClientInstance.
func (mr *MockStoreMockRecorder) UpdateDownloadClientInstance(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDownloadClientInstance", reflect.TypeOf((*MockStore)(nil).UpdateDownloadClientInstance), ctx, d)
}

// UpdateDownloadClientSettings mocks base method.
func (m *MockStore) UpdateDownloadClientSettings(ctx context.Context, s *database.DownloadClientSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDownloadClientSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDownloadClientSettings indicates an expected call of UpdateDownloadClientSettings.
func (mr *MockStoreMockRecorder) UpdateDownloadClientSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDownloadClientSettings", reflect.TypeOf((*MockStore)(nil).UpdateDownloadClientSettings), ctx, s)
}

// UpdateInstance mocks base method.
func (m *MockStore) UpdateInstance(ctx context.Context, id uuid.UUID, name, apiURL, apiKey string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", ctx, id, name, apiURL, apiKey, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockStoreMockRecorder) UpdateInstance(ctx, id, name, apiURL, apiKey, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockStore)(nil).UpdateInstance), ctx, id, name, apiURL, apiKey, enabled)
}

// UpdateInstanceGroup mocks base method.
func (m *MockStore) UpdateInstanceGroup(ctx context.Context, id uuid.UUID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceGroup", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstanceGroup indicates an expected call of UpdateInstanceGroup.
func (mr *MockStoreMockRecorder) UpdateInstanceGroup(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceGroup", reflect.TypeOf((*MockStore)(nil).UpdateInstanceGroup), ctx, id, name)
}

// UpdateInstanceGroupMode mocks base method.
func (m *MockStore) UpdateInstanceGroupMode(ctx context.Context, id uuid.UUID, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceGroupMode", ctx, id, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstanceGroupMode indicates an expected call of UpdateInstanceGroupMode.
func (mr *MockStoreMockRecorder) UpdateInstanceGroupMode(ctx, id, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceGroupMode", reflect.TypeOf((*MockStore)(nil).UpdateInstanceGroupMode), ctx, id, mode)
}

// UpdateNotificationProvider mocks base method.
func (m *MockStore) UpdateNotificationProvider(ctx context.Context, p *database.NotificationProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationProvider", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationProvider indicates an expected call of UpdateNotificationProvider.
func (mr *MockStoreMockRecorder) UpdateNotificationProvider(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationProvider", reflect.TypeOf((*MockStore)(nil).UpdateNotificationProvider), ctx, p)
}

// UpdateOIDCSettings mocks base method.
func (m *MockStore) UpdateOIDCSettings(ctx context.Context, s *database.OIDCSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOIDCSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOIDCSettings indicates an expected call of UpdateOIDCSettings.
func (mr *MockStoreMockRecorder) UpdateOIDCSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOIDCSettings", reflect.TypeOf((*MockStore)(nil).UpdateOIDCSettings), ctx, s)
}

// UpdatePassword mocks base method.
func (m *MockStore) UpdatePassword(ctx context.Context, id uuid.UUID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockStoreMockRecorder) UpdatePassword(ctx, id, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockStore)(nil).UpdatePassword), ctx, id, passwordHash)
}

// UpdateProwlarrSettings mocks base method.
func (m *MockStore) UpdateProwlarrSettings(ctx context.Context, s *database.ProwlarrSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProwlarrSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProwlarrSettings indicates an expected call of UpdateProwlarrSettings.
func (mr *MockStoreMockRecorder) UpdateProwlarrSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProwlarrSettings", reflect.TypeOf((*MockStore)(nil).UpdateProwlarrSettings), ctx, s)
}

// UpdateQueueCleanerSettings mocks base method.
func (m *MockStore) UpdateQueueCleanerSettings(ctx context.Context, s *database.QueueCleanerSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQueueCleanerSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQueueCleanerSettings indicates an expected call of UpdateQueueCleanerSettings.
func (mr *MockStoreMockRecorder) UpdateQueueCleanerSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQueueCleanerSettings", reflect.TypeOf((*MockStore)(nil).UpdateQueueCleanerSettings), ctx, s)
}

// UpdateSABnzbdSettings mocks base method.
func (m *MockStore) UpdateSABnzbdSettings(ctx context.Context, s *database.SABnzbdSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSABnzbdSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSABnzbdSettings indicates an expected call of UpdateSABnzbdSettings.
func (mr *MockStoreMockRecorder) UpdateSABnzbdSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSABnzbdSettings", reflect.TypeOf((*MockStore)(nil).UpdateSABnzbdSettings), ctx, s)
}

// UpdateSchedule mocks base method.
func (m *MockStore) UpdateSchedule(ctx context.Context, s *database.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockStoreMockRecorder) UpdateSchedule(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockStore)(nil).UpdateSchedule), ctx, s)
}

// UpdateScoringProfile mocks base method.
func (m *MockStore) UpdateScoringProfile(ctx context.Context, p *database.ScoringProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScoringProfile", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScoringProfile indicates an expected call of UpdateScoringProfile.
func (mr *MockStoreMockRecorder) UpdateScoringProfile(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScoringProfile", reflect.TypeOf((*MockStore)(nil).UpdateScoringProfile), ctx, p)
}

// UpdateSeerrSettings mocks base method.
func (m *MockStore) UpdateSeerrSettings(ctx context.Context, s *database.SeerrSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeerrSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSeerrSettings indicates an expected call of UpdateSeerrSettings.
func (mr *MockStoreMockRecorder) UpdateSeerrSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeerrSettings", reflect.TypeOf((*MockStore)(nil).UpdateSeerrSettings), ctx, s)
}

// UpdateUserAdmin mocks base method.
func (m *MockStore) UpdateUserAdmin(ctx context.Context, id uuid.UUID, isAdmin bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAdmin", ctx, id, isAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAdmin indicates an expected call of UpdateUserAdmin.
func (mr *MockStoreMockRecorder) UpdateUserAdmin(ctx, id, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAdmin", reflect.TypeOf((*MockStore)(nil).UpdateUserAdmin), ctx, id, isAdmin)
}

// UpdateUsername mocks base method.
func (m *MockStore) UpdateUsername(ctx context.Context, id uuid.UUID, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", ctx, id, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername.
func (mr *MockStoreMockRecorder) UpdateUsername(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*MockStore)(nil).UpdateUsername), ctx, id, username)
}

// UpdateWebAuthnSignCount mocks base method.
func (m *MockStore) UpdateWebAuthnSignCount(ctx context.Context, credentialID []byte, signCount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebAuthnSignCount", ctx, credentialID, signCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebAuthnSignCount indicates an expected call of UpdateWebAuthnSignCount.
func (mr *MockStoreMockRecorder) UpdateWebAuthnSignCount(ctx, credentialID, signCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebAuthnSignCount", reflect.TypeOf((*MockStore)(nil).UpdateWebAuthnSignCount), ctx, credentialID, signCount)
}

// UpsertGeneralSettings mocks base method.
func (m *MockStore) UpsertGeneralSettings(ctx context.Context, s *database.GeneralSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGeneralSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGeneralSettings indicates an expected call of UpsertGeneralSettings.
func (mr *MockStoreMockRecorder) UpsertGeneralSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGeneralSettings", reflect.TypeOf((*MockStore)(nil).UpsertGeneralSettings), ctx, s)
}

// UserCount mocks base method.
func (m *MockStore) UserCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserCount indicates an expected call of UserCount.
func (mr *MockStoreMockRecorder) UserCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCount", reflect.TypeOf((*MockStore)(nil).UserCount), ctx)
}
