// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/queuecleaner (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=queuecleaner github.com/lusoris/lurkarr/internal/queuecleaner Store
//

// Package queuecleaner is a generated GoMock package.
package queuecleaner

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddStrike mocks base method.
func (m *MockStore) AddStrike(ctx context.Context, appType database.AppType, instanceID uuid.UUID, downloadID, title, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStrike", ctx, appType, instanceID, downloadID, title, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStrike indicates an expected call of AddStrike.
func (mr *MockStoreMockRecorder) AddStrike(ctx, appType, instanceID, downloadID, title, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStrike", reflect.TypeOf((*MockStore)(nil).AddStrike), ctx, appType, instanceID, downloadID, title, reason)
}

// CountStrikes mocks base method.
func (m *MockStore) CountStrikes(ctx context.Context, appType database.AppType, instanceID uuid.UUID, downloadID string, windowHours int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountStrikes", ctx, appType, instanceID, downloadID, windowHours)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountStrikes indicates an expected call of CountStrikes.
func (mr *MockStoreMockRecorder) CountStrikes(ctx, appType, instanceID, downloadID, windowHours any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountStrikes", reflect.TypeOf((*MockStore)(nil).CountStrikes), ctx, appType, instanceID, downloadID, windowHours)
}

// GetGeneralSettings mocks base method.
func (m *MockStore) GetGeneralSettings(ctx context.Context) (*database.GeneralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx)
	ret0, _ := ret[0].(*database.GeneralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockStoreMockRecorder) GetGeneralSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockStore)(nil).GetGeneralSettings), ctx)
}

// GetQueueCleanerSettings mocks base method.
func (m *MockStore) GetQueueCleanerSettings(ctx context.Context, appType database.AppType) (*database.QueueCleanerSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueCleanerSettings", ctx, appType)
	ret0, _ := ret[0].(*database.QueueCleanerSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueCleanerSettings indicates an expected call of GetQueueCleanerSettings.
func (mr *MockStoreMockRecorder) GetQueueCleanerSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueCleanerSettings", reflect.TypeOf((*MockStore)(nil).GetQueueCleanerSettings), ctx, appType)
}

// GetSABnzbdSettings mocks base method.
func (m *MockStore) GetSABnzbdSettings(ctx context.Context) (*database.SABnzbdSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSABnzbdSettings", ctx)
	ret0, _ := ret[0].(*database.SABnzbdSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSABnzbdSettings indicates an expected call of GetSABnzbdSettings.
func (mr *MockStoreMockRecorder) GetSABnzbdSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSABnzbdSettings", reflect.TypeOf((*MockStore)(nil).GetSABnzbdSettings), ctx)
}

// GetScoringProfile mocks base method.
func (m *MockStore) GetScoringProfile(ctx context.Context, appType database.AppType) (*database.ScoringProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScoringProfile", ctx, appType)
	ret0, _ := ret[0].(*database.ScoringProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScoringProfile indicates an expected call of GetScoringProfile.
func (mr *MockStoreMockRecorder) GetScoringProfile(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScoringProfile", reflect.TypeOf((*MockStore)(nil).GetScoringProfile), ctx, appType)
}

// ListEnabledInstances mocks base method.
func (m *MockStore) ListEnabledInstances(ctx context.Context, appType database.AppType) ([]database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledInstances", ctx, appType)
	ret0, _ := ret[0].([]database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledInstances indicates an expected call of ListEnabledInstances.
func (mr *MockStoreMockRecorder) ListEnabledInstances(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledInstances", reflect.TypeOf((*MockStore)(nil).ListEnabledInstances), ctx, appType)
}

// LogBlocklist mocks base method.
func (m *MockStore) LogBlocklist(ctx context.Context, appType database.AppType, instanceID uuid.UUID, downloadID, title, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogBlocklist", ctx, appType, instanceID, downloadID, title, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogBlocklist indicates an expected call of LogBlocklist.
func (mr *MockStoreMockRecorder) LogBlocklist(ctx, appType, instanceID, downloadID, title, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogBlocklist", reflect.TypeOf((*MockStore)(nil).LogBlocklist), ctx, appType, instanceID, downloadID, title, reason)
}

// ResetStrikes mocks base method.
func (m *MockStore) ResetStrikes(ctx context.Context, appType database.AppType, instanceID uuid.UUID, downloadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetStrikes", ctx, appType, instanceID, downloadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetStrikes indicates an expected call of ResetStrikes.
func (mr *MockStoreMockRecorder) ResetStrikes(ctx, appType, instanceID, downloadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetStrikes", reflect.TypeOf((*MockStore)(nil).ResetStrikes), ctx, appType, instanceID, downloadID)
}
