// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/lurking (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=lurking github.com/lusoris/lurkarr/internal/lurking Store
//

// Package lurking is a generated GoMock package.
package lurking

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddLurkHistory mocks base method.
func (m *MockStore) AddLurkHistory(ctx context.Context, appType database.AppType, instanceID uuid.UUID, instanceName string, mediaID int, title, lurkType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLurkHistory", ctx, appType, instanceID, instanceName, mediaID, title, lurkType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLurkHistory indicates an expected call of AddLurkHistory.
func (mr *MockStoreMockRecorder) AddLurkHistory(ctx, appType, instanceID, instanceName, mediaID, title, lurkType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLurkHistory", reflect.TypeOf((*MockStore)(nil).AddLurkHistory), ctx, appType, instanceID, instanceName, mediaID, title, lurkType)
}

// GetAppSettings mocks base method.
func (m *MockStore) GetAppSettings(ctx context.Context, appType database.AppType) (*database.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSettings", ctx, appType)
	ret0, _ := ret[0].(*database.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSettings indicates an expected call of GetAppSettings.
func (mr *MockStoreMockRecorder) GetAppSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSettings", reflect.TypeOf((*MockStore)(nil).GetAppSettings), ctx, appType)
}

// GetCurrentHourHits mocks base method.
func (m *MockStore) GetCurrentHourHits(ctx context.Context, appType database.AppType, instanceID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentHourHits", ctx, appType, instanceID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentHourHits indicates an expected call of GetCurrentHourHits.
func (mr *MockStoreMockRecorder) GetCurrentHourHits(ctx, appType, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentHourHits", reflect.TypeOf((*MockStore)(nil).GetCurrentHourHits), ctx, appType, instanceID)
}

// GetGeneralSettings mocks base method.
func (m *MockStore) GetGeneralSettings(ctx context.Context) (*database.GeneralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx)
	ret0, _ := ret[0].(*database.GeneralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockStoreMockRecorder) GetGeneralSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockStore)(nil).GetGeneralSettings), ctx)
}

// GetLastReset mocks base method.
func (m *MockStore) GetLastReset(ctx context.Context, appType database.AppType, instanceID uuid.UUID) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReset", ctx, appType, instanceID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReset indicates an expected call of GetLastReset.
func (mr *MockStoreMockRecorder) GetLastReset(ctx, appType, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReset", reflect.TypeOf((*MockStore)(nil).GetLastReset), ctx, appType, instanceID)
}

// IncrementHourlyHits mocks base method.
func (m *MockStore) IncrementHourlyHits(ctx context.Context, appType database.AppType, instanceID uuid.UUID, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementHourlyHits", ctx, appType, instanceID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementHourlyHits indicates an expected call of IncrementHourlyHits.
func (mr *MockStoreMockRecorder) IncrementHourlyHits(ctx, appType, instanceID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementHourlyHits", reflect.TypeOf((*MockStore)(nil).IncrementHourlyHits), ctx, appType, instanceID, count)
}

// IncrementStats mocks base method.
func (m *MockStore) IncrementStats(ctx context.Context, appType database.AppType, instanceID uuid.UUID, missing, upgrades int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementStats", ctx, appType, instanceID, missing, upgrades)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementStats indicates an expected call of IncrementStats.
func (mr *MockStoreMockRecorder) IncrementStats(ctx, appType, instanceID, missing, upgrades any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementStats", reflect.TypeOf((*MockStore)(nil).IncrementStats), ctx, appType, instanceID, missing, upgrades)
}

// IsProcessed mocks base method.
func (m *MockStore) IsProcessed(ctx context.Context, appType database.AppType, instanceID uuid.UUID, mediaID int, lurkType string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProcessed", ctx, appType, instanceID, mediaID, lurkType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProcessed indicates an expected call of IsProcessed.
func (mr *MockStoreMockRecorder) IsProcessed(ctx, appType, instanceID, mediaID, lurkType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProcessed", reflect.TypeOf((*MockStore)(nil).IsProcessed), ctx, appType, instanceID, mediaID, lurkType)
}

// ListEnabledInstances mocks base method.
func (m *MockStore) ListEnabledInstances(ctx context.Context, appType database.AppType) ([]database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledInstances", ctx, appType)
	ret0, _ := ret[0].([]database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledInstances indicates an expected call of ListEnabledInstances.
func (mr *MockStoreMockRecorder) ListEnabledInstances(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledInstances", reflect.TypeOf((*MockStore)(nil).ListEnabledInstances), ctx, appType)
}

// MarkProcessed mocks base method.
func (m *MockStore) MarkProcessed(ctx context.Context, appType database.AppType, instanceID uuid.UUID, mediaID int, lurkType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, appType, instanceID, mediaID, lurkType)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockStoreMockRecorder) MarkProcessed(ctx, appType, instanceID, mediaID, lurkType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockStore)(nil).MarkProcessed), ctx, appType, instanceID, mediaID, lurkType)
}

// ResetState mocks base method.
func (m *MockStore) ResetState(ctx context.Context, appType database.AppType, instanceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetState", ctx, appType, instanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetState indicates an expected call of ResetState.
func (mr *MockStoreMockRecorder) ResetState(ctx, appType, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetState", reflect.TypeOf((*MockStore)(nil).ResetState), ctx, appType, instanceID)
}
