// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/lurking (interfaces: ArrLurker)
//
// Generated by this command:
//
//	mockgen -destination=mock_arrlurker_test.go -package=lurking github.com/lusoris/lurkarr/internal/lurking ArrLurker
//

// Package lurking is a generated GoMock package.
package lurking

import (
	context "context"
	reflect "reflect"

	arrclient "github.com/lusoris/lurkarr/internal/arrclient"
	gomock "go.uber.org/mock/gomock"
)

// MockArrLurker is a mock of ArrLurker interface.
type MockArrLurker struct {
	ctrl     *gomock.Controller
	recorder *MockArrLurkerMockRecorder
	isgomock struct{}
}

// MockArrLurkerMockRecorder is the mock recorder for MockArrLurker.
type MockArrLurkerMockRecorder struct {
	mock *MockArrLurker
}

// NewMockArrLurker creates a new mock instance.
func NewMockArrLurker(ctrl *gomock.Controller) *MockArrLurker {
	mock := &MockArrLurker{ctrl: ctrl}
	mock.recorder = &MockArrLurkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrLurker) EXPECT() *MockArrLurkerMockRecorder {
	return m.recorder
}

// GetMissing mocks base method.
func (m *MockArrLurker) GetMissing(ctx context.Context, c *arrclient.Client) ([]lurkableItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMissing", ctx, c)
	ret0, _ := ret[0].([]lurkableItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMissing indicates an expected call of GetMissing.
func (mr *MockArrLurkerMockRecorder) GetMissing(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMissing", reflect.TypeOf((*MockArrLurker)(nil).GetMissing), ctx, c)
}

// GetQueue mocks base method.
func (m *MockArrLurker) GetQueue(ctx context.Context, c *arrclient.Client) (*arrclient.QueueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueue", ctx, c)
	ret0, _ := ret[0].(*arrclient.QueueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueue indicates an expected call of GetQueue.
func (mr *MockArrLurkerMockRecorder) GetQueue(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueue", reflect.TypeOf((*MockArrLurker)(nil).GetQueue), ctx, c)
}

// GetUpgrades mocks base method.
func (m *MockArrLurker) GetUpgrades(ctx context.Context, c *arrclient.Client) ([]lurkableItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgrades", ctx, c)
	ret0, _ := ret[0].([]lurkableItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpgrades indicates an expected call of GetUpgrades.
func (mr *MockArrLurkerMockRecorder) GetUpgrades(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgrades", reflect.TypeOf((*MockArrLurker)(nil).GetUpgrades), ctx, c)
}

// Search mocks base method.
func (m *MockArrLurker) Search(ctx context.Context, c *arrclient.Client, mediaID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, c, mediaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Search indicates an expected call of Search.
func (mr *MockArrLurkerMockRecorder) Search(ctx, c, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockArrLurker)(nil).Search), ctx, c, mediaID)
}
