// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/scheduler (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=scheduler github.com/lusoris/lurkarr/internal/scheduler Store
//

// Package scheduler is a generated GoMock package.
package scheduler

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddScheduleExecution mocks base method.
func (m *MockStore) AddScheduleExecution(ctx context.Context, scheduleID uuid.UUID, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddScheduleExecution", ctx, scheduleID, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddScheduleExecution indicates an expected call of AddScheduleExecution.
func (mr *MockStoreMockRecorder) AddScheduleExecution(ctx, scheduleID, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddScheduleExecution", reflect.TypeOf((*MockStore)(nil).AddScheduleExecution), ctx, scheduleID, result)
}

// CleanupOldHourlyCaps mocks base method.
func (m *MockStore) CleanupOldHourlyCaps(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldHourlyCaps", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupOldHourlyCaps indicates an expected call of CleanupOldHourlyCaps.
func (mr *MockStoreMockRecorder) CleanupOldHourlyCaps(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldHourlyCaps", reflect.TypeOf((*MockStore)(nil).CleanupOldHourlyCaps), ctx)
}

// GetAppSettings mocks base method.
func (m *MockStore) GetAppSettings(ctx context.Context, appType database.AppType) (*database.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSettings", ctx, appType)
	ret0, _ := ret[0].(*database.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSettings indicates an expected call of GetAppSettings.
func (mr *MockStoreMockRecorder) GetAppSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSettings", reflect.TypeOf((*MockStore)(nil).GetAppSettings), ctx, appType)
}

// ListInstances mocks base method.
func (m *MockStore) ListInstances(ctx context.Context, appType database.AppType) ([]database.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, appType)
	ret0, _ := ret[0].([]database.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockStoreMockRecorder) ListInstances(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockStore)(nil).ListInstances), ctx, appType)
}

// ListSchedules mocks base method.
func (m *MockStore) ListSchedules(ctx context.Context) ([]database.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx)
	ret0, _ := ret[0].([]database.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockStoreMockRecorder) ListSchedules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockStore)(nil).ListSchedules), ctx)
}

// UpdateAppSettings mocks base method.
func (m *MockStore) UpdateAppSettings(ctx context.Context, s *database.AppSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppSettings indicates an expected call of UpdateAppSettings.
func (mr *MockStoreMockRecorder) UpdateAppSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppSettings", reflect.TypeOf((*MockStore)(nil).UpdateAppSettings), ctx, s)
}

// UpdateInstance mocks base method.
func (m *MockStore) UpdateInstance(ctx context.Context, id uuid.UUID, name, apiURL, apiKey string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", ctx, id, name, apiURL, apiKey, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockStoreMockRecorder) UpdateInstance(ctx, id, name, apiURL, apiKey, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockStore)(nil).UpdateInstance), ctx, id, name, apiURL, apiKey, enabled)
}
