// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lusoris/lurkarr/internal/hunting (interfaces: ArrHunter)
//
// Generated by this command:
//
//	mockgen -destination=mock_arrhunter_test.go -package=hunting github.com/lusoris/lurkarr/internal/hunting ArrHunter
//

// Package hunting is a generated GoMock package.
package hunting

import (
	context "context"
	reflect "reflect"

	arrclient "github.com/lusoris/lurkarr/internal/arrclient"
	gomock "go.uber.org/mock/gomock"
)

// MockArrHunter is a mock of ArrHunter interface.
type MockArrHunter struct {
	ctrl     *gomock.Controller
	recorder *MockArrHunterMockRecorder
	isgomock struct{}
}

// MockArrHunterMockRecorder is the mock recorder for MockArrHunter.
type MockArrHunterMockRecorder struct {
	mock *MockArrHunter
}

// NewMockArrHunter creates a new mock instance.
func NewMockArrHunter(ctrl *gomock.Controller) *MockArrHunter {
	mock := &MockArrHunter{ctrl: ctrl}
	mock.recorder = &MockArrHunterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrHunter) EXPECT() *MockArrHunterMockRecorder {
	return m.recorder
}

// GetMissing mocks base method.
func (m *MockArrHunter) GetMissing(ctx context.Context, c *arrclient.Client) ([]huntableItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMissing", ctx, c)
	ret0, _ := ret[0].([]huntableItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMissing indicates an expected call of GetMissing.
func (mr *MockArrHunterMockRecorder) GetMissing(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMissing", reflect.TypeOf((*MockArrHunter)(nil).GetMissing), ctx, c)
}

// GetQueue mocks base method.
func (m *MockArrHunter) GetQueue(ctx context.Context, c *arrclient.Client) (*arrclient.QueueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueue", ctx, c)
	ret0, _ := ret[0].(*arrclient.QueueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueue indicates an expected call of GetQueue.
func (mr *MockArrHunterMockRecorder) GetQueue(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueue", reflect.TypeOf((*MockArrHunter)(nil).GetQueue), ctx, c)
}

// GetUpgrades mocks base method.
func (m *MockArrHunter) GetUpgrades(ctx context.Context, c *arrclient.Client) ([]huntableItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgrades", ctx, c)
	ret0, _ := ret[0].([]huntableItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpgrades indicates an expected call of GetUpgrades.
func (mr *MockArrHunterMockRecorder) GetUpgrades(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgrades", reflect.TypeOf((*MockArrHunter)(nil).GetUpgrades), ctx, c)
}

// Search mocks base method.
func (m *MockArrHunter) Search(ctx context.Context, c *arrclient.Client, mediaID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, c, mediaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Search indicates an expected call of Search.
func (mr *MockArrHunterMockRecorder) Search(ctx, c, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockArrHunter)(nil).Search), ctx, c, mediaID)
}
