// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -destination=mock_settingsloader_test.go -package=cache -source=cache.go -mock_names=settingsLoader=MockSettingsLoader
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"

	database "github.com/lusoris/lurkarr/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsLoader is a mock of settingsLoader interface.
type MockSettingsLoader struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsLoaderMockRecorder
	isgomock struct{}
}

// MockSettingsLoaderMockRecorder is the mock recorder for MockSettingsLoader.
type MockSettingsLoaderMockRecorder struct {
	mock *MockSettingsLoader
}

// NewMockSettingsLoader creates a new mock instance.
func NewMockSettingsLoader(ctrl *gomock.Controller) *MockSettingsLoader {
	mock := &MockSettingsLoader{ctrl: ctrl}
	mock.recorder = &MockSettingsLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsLoader) EXPECT() *MockSettingsLoaderMockRecorder {
	return m.recorder
}

// GetAppSettings mocks base method.
func (m *MockSettingsLoader) GetAppSettings(ctx context.Context, appType database.AppType) (*database.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSettings", ctx, appType)
	ret0, _ := ret[0].(*database.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSettings indicates an expected call of GetAppSettings.
func (mr *MockSettingsLoaderMockRecorder) GetAppSettings(ctx, appType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSettings", reflect.TypeOf((*MockSettingsLoader)(nil).GetAppSettings), ctx, appType)
}

// GetGeneralSettings mocks base method.
func (m *MockSettingsLoader) GetGeneralSettings(ctx context.Context) (*database.GeneralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx)
	ret0, _ := ret[0].(*database.GeneralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockSettingsLoaderMockRecorder) GetGeneralSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockSettingsLoader)(nil).GetGeneralSettings), ctx)
}
